version: '3.1'

services:
  user-transaction:
    build: .
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - /postgres2:/var/lib/postgresql/data2
    environment:
      - 'POSTGRES_DB=userdb'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
